services:
  cloudchampion-web:
    container_name: cloudchampion-web
    image: cloudchampion/web
    build:
      context: .
      dockerfile: Frontend/CloudChampion.Web/Dockerfile
    depends_on:
      - rabbitmq
      - redis

  cloudchampion-web-dapr:
    container_name: cloudchampion-web-dapr
    image: "daprio/daprd:1.7.3"
    network_mode: "service:cloudchampion-web"
    depends_on:
      - cloudchampion-web
  
  cloudchampion-order:
    container_name: cloudchampion-order
    image: cloudchampion/order
    build:
      context: .
      dockerfile: Services/CloudChampion.Order/Dockerfile
    depends_on:
      - rabbitmq
      - redis
  
  cloudchampion-order-dapr:
    container_name: cloudchampion-order-dapr
    image: "daprio/daprd:1.7.3"
    network_mode: "service:cloudchampion-order"
    depends_on:
      - cloudchampion-order
  
  cloudchampion-warehouse:
    container_name: cloudchampion-warehouse
    image: cloudchampion/warehouse
    build:
      context: .
      dockerfile: Services/CloudChampion.warehouse/Dockerfile
    depends_on:
      - rabbitmq
      - redis
  
  cloudchampion-warehouse-dapr:
    container_name: cloudchampion-warehouse-dapr
    image: "daprio/daprd:1.7.3"
    network_mode: "service:cloudchampion-warehouse"
    depends_on:
      - cloudchampion-warehouse

  #Pub-Sub
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management

  #State
  redis:
    container_name: redis
    image: redis:alpine

  # Observability
  #zipkin:
  #  container_name: zipkin
  #  image: openzipkin/zipkin-slim

  #jeager:
  #  container_name: jeager
  #  image: jaegertracing/all-in-one:1.23

  #otel-collector:
  #  container_name: otel-collector
  #  image: otel/opentelemetry-collector-contrib-dev:latest
